### ISSUE TITLE
IndexOutOfBoundsException thrown out while tab-completing commands

### ISSUE THREAD

**Issue by AlenGeoAlex** [TriumphTeam/triumph-cmds#86]
An IndexOutOfBoundsException has been thrown while the plugin tries to grab the subcommands, 
The source code which caused the error: https://pastes.dev/olhk9PDkHM

The relevant stacktrace for that is
```
[17:31:17 ERROR]: Exception when Alen_Alex attempted to tab complete gladiator start
org.bukkit.command.CommandException: Unhandled exception executing tab-completer for 'gladiator start' in io.github.alenalex.gladiator.shaded.cmd.bukkit.BukkitCommand(gladiator)
        at org.bukkit.command.SimpleCommandMap.tabComplete(SimpleCommandMap.java:221) ~[server.jar:git-Spigot-596221b-9a1fc1e]
        at org.bukkit.command.SimpleCommandMap.tabComplete(SimpleCommandMap.java:169) ~[server.jar:git-Spigot-596221b-9a1fc1e]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.tabCompleteCommand(CraftServer.java:1607) [server.jar:git-Spigot-596221b-9a1fc1e]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.tabComplete(CraftServer.java:1581) [server.jar:git-Spigot-596221b-9a1fc1e]
        at net.minecraft.server.v1_12_R1.MinecraftServer.tabCompleteCommand(MinecraftServer.java:1124) [server.jar:git-Spigot-596221b-9a1fc1e]
        at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:2244) [server.jar:git-Spigot-596221b-9a1fc1e]
        at net.minecraft.server.v1_12_R1.PacketPlayInTabComplete.a(SourceFile:52) [server.jar:git-Spigot-596221b-9a1fc1e]
        at net.minecraft.server.v1_12_R1.PacketPlayInTabComplete.a(SourceFile:11) [server.jar:git-Spigot-596221b-9a1fc1e]
        at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13) [server.jar:git-Spigot-596221b-9a1fc1e]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) [?:?]
        at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
        at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [server.jar:git-Spigot-596221b-9a1fc1e]
        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:747) [server.jar:git-Spigot-596221b-9a1fc1e]
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:405) [server.jar:git-Spigot-596221b-9a1fc1e]
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:678) [server.jar:git-Spigot-596221b-9a1fc1e]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:576) [server.jar:git-Spigot-596221b-9a1fc1e]
        at java.lang.Thread.run(Thread.java:829) [?:?]
Caused by: java.lang.IndexOutOfBoundsException: Index -1 out of bounds for length 1
        at jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64) ~[?:?]
        at jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70) ~[?:?]
        at jdk.internal.util.Preconditions.checkIndex(Preconditions.java:248) ~[?:?]
        at java.util.Objects.checkIndex(Objects.java:372) ~[?:?]
        at java.util.ArrayList.get(ArrayList.java:459) ~[?:?]
        at io.github.alenalex.gladiator.shaded.cmd.core.AbstractSubCommand.getArgument(AbstractSubCommand.java:217) ~[?:?]
        at io.github.alenalex.gladiator.shaded.cmd.bukkit.BukkitSubCommand.getSuggestions(BukkitSubCommand.java:51) ~[?:?]
        at io.github.alenalex.gladiator.shaded.cmd.bukkit.BukkitCommand.tabComplete(BukkitCommand.java:140) ~[?:?]
        at org.bukkit.command.Command.tabComplete(Command.java:90) ~[server.jar:git-Spigot-596221b-9a1fc1e]
        at org.bukkit.command.SimpleCommandMap.tabComplete(SimpleCommandMap.java:217) ~[server.jar:git-Spigot-596221b-9a1fc1e]
        ... 16 more
      ```

**Comment by LichtHund** [comment]
Fixed on #84.
