### ISSUE TITLE
Plugin x tried to register permission 'x' but it's already registered

### ISSUE THREAD

**Issue by HexedHero** [TriumphTeam/triumph-cmds#91]
If you have a command with the permission annotation, on startup it'll complain about triumph-cmds registering the permission if it's already in the plugin.yml. **This seems to only be an issue on 1.8 and 1.9 for whatever reason**

Problematic code: https://github.com/TriumphTeam/triumph-cmds/blob/master/minecraft/bukkit/src/main/java/dev/triumphteam/cmd/bukkit/CommandPermission.java#L92-L102

```
[14:45:41 WARN]: Plugin CitizensCMD v2.6.11 tried to register permission 'citizenscmd.edit' but it's already registered
java.lang.IllegalArgumentException: The permission citizenscmd.edit is already defined!
	at org.bukkit.plugin.SimplePluginManager.addPermission(SimplePluginManager.java:621) ~[patched_1.8.8.jar:git-PaperSpigot-445]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:365) [patched_1.8.8.jar:git-PaperSpigot-445]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:318) [patched_1.8.8.jar:git-PaperSpigot-445]
	at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:408) [patched_1.8.8.jar:git-PaperSpigot-445]
	at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:372) [patched_1.8.8.jar:git-PaperSpigot-445]
	at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:327) [patched_1.8.8.jar:git-PaperSpigot-445]
	at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:267) [patched_1.8.8.jar:git-PaperSpigot-445]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:563) [patched_1.8.8.jar:git-PaperSpigot-445]
	at java.lang.Thread.run(Thread.java:750) [?:1.8.0_372]
```

**Comment by EvilG-MC** [comment]
This error has been active for a year and has not been answered or resolved ☠️
